Update performance benchmarks to take CPU frame time.
o3de/o3de-atom-sampleviewer pull request #188
Opened 2021-08-06 17:10 UTC by synicalsyntax

Companion PR to o3de/o3de#2939

2021-08-06 20:59 UTC, wintermute-motherbrain approved these changes

2021-08-09 18:15 UTC, hershey5045 approved these changes

2021-08-09 18:15 UTC, hershey5045 commented on Gem/Code/Source/Automation/ScriptManager.cpp
> +    void ScriptManager::Script_CaptureCpuFrameTime(AZ::ScriptDataContext& dc)
should this be const AZ::ScriptDataContext& dc?

2021-08-09 18:15 UTC, hershey5045 commented on Gem/Code/Source/Automation/ScriptManager.cpp
> +    void ScriptManager::Script_CaptureCpuFrameTime(AZ::ScriptDataContext& dc)
I know other script functions do not declare this as const, just wondering if it ought to be.

2021-08-09 20:02 UTC, jromnoa requested changes

2021-08-09 20:02 UTC, jromnoa commented on Scripts/_AutomatedPeriodicBenchmarkSuite_.bv.lua
> +        cpu_timings = output_path .. '/cpu_frame' ..tostring(i) .. '_time.json'
need a space after `..` and before `tostring(i`)

2021-08-09 20:40 UTC, jromnoa approved these changes

2021-08-09 21:58 UTC, merged